name: Code quality assurance
description: Action designed to enforce Code Quality Assurance by automating checks for code formatting, linting, testing, and build verification

inputs:
  GH_TOKEN:
    description: "A GitHub PAT"
    required: true

runs:
  using: composite
  steps:
    - id: CI-00
      name: Install NPM dependencies
      uses: exile-watch/doryani/install-npm-dependencies@main
      with:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

    - id: CI-01
      name: Setup Biome CLI
      uses: biomejs/setup-biome@v2
      with:
        token: ${{ inputs.GH_TOKEN }}

    - name: Run Biome
      shell: bash
      run: biome ci

    - id: CI-02
      name: Run type check
      run: npm run ci:typecheck
      shell: bash

    - id: CI-03
      name: Run tests
      run: npm run test
      shell: bash