name: Code quality assurance
description: Action designed to enforce Code Quality Assurance by automating checks for code formatting, linting, testing, and build verification

inputs:
  GH_TOKEN:
    description: "A GitHub PAT"
    required: true
  GH_ACTOR:
    description: "A GitHub actor"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - id: CI-00
      name: Authenticate to GitHub Registry
      uses: exile-watch/doryani/auth-github-registry@main
      with:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
        GH_ACTOR: ${{ inputs.GH_ACTOR }}

    - id: CI-01
      name: Install dependencies
      run: npm ci
      shell: bash

    - id: CI-02
      name: Run code quality script (format + lint + typecheck)
      run: npm run cq
      shell: bash

    - id: CI-03
      name: Run tests
      run: npm run test
      shell: bash

    - id: CI-04
      name: Run build
      run: npm run build
      shell: bash