name: Preview publish package - 01 - Publish pre-release
description: Creates prerelease in x.x.x-preview.x format and publishes to github registry

inputs:
  GH_TOKEN:
    description: A GitHub PAT
    required: true
  GH_ACTOR:
    description: A GitHub username
    required: true
  prRef:
    description: Pull request reference, e.g. `github.event.pull_request.head.ref`
    required: true

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.GH_TOKEN }}
        fetch-depth: 0
        ref: ${{ inputs.prRef }}

    - uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: npm

    - name: Configure Git
      run: |
        git config --global user.name "${{ inputs.GH_ACTOR }}"
        git config --global user.email "${{ inputs.GH_ACTOR }}@users.noreply.github.com"
      shell: bash

    - name: GitHub Package Registry Identity
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > .npmrc
        echo "@exile-watch:registry=https://npm.pkg.github.com/" >> .npmrc
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Build
      run: npm run build
      shell: bash

    - name: Lerna publish pre-release
      id: publish-prerelease
      env:
        CI: true
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        npx lerna publish from-git --canary --preid preview --yes
        npx lerna changed --json | jq -c >> changelog.json
      shell: bash

    - name: Upload changelog as an artifact
      if: steps.publish-prerelease.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: changelog-artifact
        path: changelog.json
        retention-days: 1
