name: Preview publish package - 01 - Publish pre-release
description: Creates prerelease in x.x.x-preview.x format and publishes to github registry

inputs:
  GH_TOKEN:
    description: A GitHub PAT
    required: true
  prRef:
    description: Pull request reference, e.g. `github.event.pull_request.head.ref`
    required: true

runs:
  using: composite
  steps:
    - name: Install NPM dependencies
      uses: exile-watch/doryani/install-npm-dependencies@main
      with:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

    - name: Lerna publish pre-release
      id: publish-prerelease
      env:
        CI: true
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        npx lerna publish --canary --no-git-reset --preid preview --yes
        npx lerna changed --json | jq -c >> changelog.json
      shell: bash

    - name: Upload changelog as an artifact
      if: steps.publish-prerelease.outcome == 'success'
      uses: actions/upload-artifact@v4
      with:
        name: changelog-artifact
        path: changelog.json
        retention-days: 1
