name: Deploy webapp to Cloudflare Pages
description: Action designed to automate the deployment of web applications to Cloudflare Pages

inputs:
  CLOUDFLARE_API_TOKEN:
    description: A Cloudflare API token
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: A Cloudflare account ID
    required: true
  PROJECT_NAME:
    description: "Cloudflare Pages project name"
    required: true
  ENV:
    description: "An environment to deploy to: <beta|production>"
    required: true
  GH_TOKEN:
    description: "A GitHub PAT"
    required: true
  GH_ACTOR:
    description: "A GitHub actor"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Configure Git
      run: |
        git config --global user.name "${{ inputs.GH_ACTOR }}"
        git config --global user.email "${{ inputs.GH_ACTOR }}@users.noreply.github.com"
      shell: bash

    - name: GitHub Package Registry Identity
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
      run: |
        echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > .npmrc
        echo "@exile-watch:registry=https://npm.pkg.github.com/" >> .npmrc
      shell: bash

    - name: Install dependencies
      run: npm ci
      shell: bash

    - name: Test
      run: npm run test
      shell: bash

    - name: Build
      run: npm run build && mkdir .vercel/output/static && mv .next/static .vercel/output/static
      shell: bash

    - name: Build & Deploy Worker
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        directory: ".vercel/output/static"
        gitHubToken: ${{ inputs.GH_TOKEN }}
        wranglerVersion: '3'
