name: Preview publish package - 02 - Update status comment on success
description: Once the package is published, this workflow updates the status created in 00-create-status

inputs:
  GH_TOKEN:
    description: A GitHub PAT
    required: true
  prRef:
    description: Pull request reference, e.g. `github.event.pull_request.head.ref`
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.GH_TOKEN }}
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        path: ./

    - name: Read artifacts
      run: |
        echo "comment_id=$(cat ./comment-artifact/comment_id.txt)" >> $GITHUB_ENV
        echo "changelog=$(cat ./changelog-artifact/changelog.json | base64)" >> $GITHUB_ENV
      shell: bash

    - name: Update status comment
      uses: actions/github-script@v7
      with:
        script: |
          const comment_id = ${{ env.comment_id }}
          const encodedChangelog = ${{ env.changelog }};
          const decodedChangelog = Buffer.from(encodedChangelog, 'base64').toString('utf-8')
          console.log(decodedChangelog, JSON.parse(decodedChangelog))
          const changelog = decodedChangelog.length > 0 ? JSON.parse(decodedChangelog)?.map(c => `${c.name}@${c.version}`).join('\\n') : null;

          if(!changelog){
            github.rest.issues.updateComment({
              ...context.repo,
              comment_id: comment_id,
              body: `> [!NOTE]
          > Pre-Release skipped. 

          No changes were made.
              `
            });

            return;
          }

          github.rest.issues.updateComment({
            ...context.repo,
            comment_id: comment_id,
            body: `> [!TIP]
            > Pre-Release created

            The pre-release has been successfully created for the following packages:
            \`\`\`
            ${changelog}
            \`\`\`
            You can now check out the latest version.
            `
          });