name: Preview deploy webapp - 04 - Remove preview-deploy label
description: Removes preview-deploy label from PR once CI-00 is completed

inputs:
  GH_TOKEN:
    description: A GitHub PAT
    required: true
  prRef:
    description: Pull request reference, e.g. `github.event.pull_request.head.ref`
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.GH_TOKEN }}
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Remove preview-publish label
      uses: actions/github-script@v7
      with:
        script: |
          const labelToRemove = 'preview-deploy'

          // Check if the PR already has the label
          const { data: labels } = await github.rest.issues.listLabelsOnIssue({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          });

          const hasLabel = labels.some(label => label.name === labelToRemove);

          if(!hasLabel) return;

          github.rest.issues.removeLabel({
            ...context.repo,
            issue_number: context.issue.number,
            name: [labelToRemove]
          });