name: Authenticate to GitHub Package Registry
description: Action designed to automate the authentication process with GitHub Package Registry

inputs:
  GH_TOKEN:
    description: "A GitHub PAT"
    required: true

runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.GH_TOKEN }}
        fetch-depth: 0 # Fetch-depth 0 necessary to get full commit history for checking changes

    - name: Setup GitHub Package Registry Identity
      uses: actions/setup-node@v4
      with:
        node-version: 20
        token: ${{ inputs.GH_TOKEN }}
        registry-url: https://npm.pkg.github.com
        scope: "@exile-watch"

    - name: Configure Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git