name: Publish package
description: Action designed to automate the process of publishing a Lerna package to a github npm registry

inputs:
  GH_TOKEN:
    description: "A GitHub PAT"
    required: true
  NPM_TOKEN:
    description: "An NPM token"
    required: true

runs:
  using: composite
  steps:
    - uses: exile-watch/doryani/install-npm-dependencies@main
      with:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

    - name: Run build script
      run: npm run build
      shell: bash

    - name: Tag, publish and release
      shell: bash
      run: npm run release
      env:
        GH_TOKEN: ${{ inputs.GH_TOKEN }}
