name: Publish package
description: Action designed to automate the process of publishing a Lerna package to a github npm registry

inputs:
  GH_TOKEN:
    description: "A GitHub PAT"
    required: true
  NPM_TOKEN:
    description: "An NPM token"
    required: true
  GH_ACTOR:
    description: "A GitHub actor"
    required: true

runs:
  using: composite
  steps:
    - uses: exile-watch/doryani/install-npm-dependencies@main
      with:
        GH_ACTOR: ${{ inputs.GH_ACTOR }}
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

#    - name: Build
#      shell: bash
#      run: npm run build

    - name: Create Release Pull Request or Publish
      uses: changesets/action@v1
      with:
        publish: npm run publish-packages
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}