name: Publish package
description: Action designed to automate the process of publishing a Lerna package to a github npm registry

inputs:
  GH_TOKEN:
    description: "A GitHub PAT"
    required: true
  NPM_TOKEN:
    description: "An NPM token"
    required: true
  GH_ACTOR:
    description: "A GitHub actor"
    required: true

runs:
  using: composite
  steps:
    - uses: exile-watch/doryani/install-npm-dependencies@main
      with:
        GH_ACTOR: ${{ inputs.GH_ACTOR }}
        GH_TOKEN: ${{ inputs.GH_TOKEN }}

#    - name: Build
#      shell: bash
#      run: npm run build

    - uses: peterjgrainger/action-create-branch@v2.2.0
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        branch: 'changeset-release/main'
        sha: '${{ github.event.pull_request.head.sha }}'

    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.GH_TOKEN }}
        fetch-depth: 0
        ref: changeset-release/main

    - name: Generate Changesets
      run: npx changeset-conventional-commits
      shell: bash

    - name: Create Release Pull Request or Publish
      uses: changesets/action@v1
      with:
        publish: npm run publish-packages
      env:
        GITHUB_TOKEN: ${{ inputs.GH_TOKEN }}
        NPM_TOKEN: ${{ inputs.NPM_TOKEN }}